### ISSUE TITLE
[Question] Nuget package?

### ISSUE THREAD

**Issue by loctanvo** [vidarkongsli/flowcontrolextensions#1]
Hi Vidar,

I'd like to use your flowcontrolextensions. Are you considering creating a NuGet package? We had similar functionality implemented in my previous project, but I recently changed client, so we'd need to re-implement everything. Unless I use your implementation though :) .

Loc

**Comment by loctanvo** [comment]
Oh, just saw that the implementation is quite lean, so if it's ok, I'll "borrow" (copy/paste) your FlowControlExtensions class(es) in the mean time. Maybe a NuGet package would be a bit overkill at this stage.

**Comment by vidarkongsli** [comment]
Sorry for the delay, but nuget package is coming. Any tips on a free CI-as-a-service to use?

**Comment by loctanvo** [comment]
Cool. I'm happy with http://www.appveyor.com/ . Using it to push to both NuGet.org and MyGet for pre-release.

**Comment by vidarkongsli** [comment]
A prerelease Nuget package is out.

```
PM> Install-Package gowiththeflow -Pre
```

Check it out :-)

**Comment by loctanvo** [comment]
:+1: , thanks!
